site_name: Railduino 2.1 Documentation
docs_dir: docs
site_dir: site
theme:
  name: material
  palette:
    primary: indigo
  icon:
    admonition:
      warning: octicons/alert-16
  features:
    - content.code.copy
    - content.tabs
    - search.suggest
extra_css:
    - stylesheets/extra.css
nav:
  - Home: index.md
  - General: general.md
  - Description: description.md
  - Commisioning: installation.md
  - Connection: connection.md
  - Webserver: webserver.md
  - Modbus settings: modbus.md
  - UDP settings: udp.md
  - Loxone Examples - Modbus: modbus_examples.md
  - Loxone Examples - UDP: udp_examples.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - tables
  - fenced_code
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
repo_url: https://github.com/PavSedl/RAILDUINO
site_url: https://PavSedl.github.io/RAILDUINO