name: Deploy MkDocs
on:
  push:
    branches: [ main ]
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs==1.6.0 mkdocs-material==9.5.39 mkdocs-mermaid2-plugin==1.2.1
      - run: mkdocs gh-deploy --force --config-file mkdocs.yml